version: '3.9'

services:
  rabbitmq:
    image: rabbitmq:3.11-management
    container_name: rabbitmq
    ports:
      - "15672:15672"

    environment:
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    networks:
      - notification-service

  postgres:
    image: postgres:14.2-alpine
    container_name: postgres
    environment:
      - POSTGRES_DB=${POSTGRES_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - notification-service

  notification-worker:
    build:
      context: ./rabbit_worker
      dockerfile: Dockerfile
    container_name: notification-worker
    depends_on:
      - rabbitmq
    env_file:
      - .env
    restart: always
    networks:
      - notification-service

  notification-api:
    build:
      context: ./notification_api_service
      dockerfile: Dockerfile
    container_name: notification-api
    depends_on:
      - postgres
    env_file:
      - .env
    restart: always
    networks:
      - notification-service
    ports:
      - "8001:8001"

networks:
  notification-service:
    driver: bridge
