"""do migration

Revision ID: 83377fa94c55
Revises: 
Create Date: 2022-11-21 02:38:30.714889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83377fa94c55'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
